package vr

const (
	ApplicationEntity   = "AE"
	AgeString           = "AS"
	AttributeTag        = "AT"
	CodeString          = "CS"
	Date                = "DA"
	DecimalString       = "DS"
	DateTime            = "DT"
	FloatingPointSingle = "FL"
	FloatingPointDouble = "FD"
	IntegerString       = "IS"
	LongString          = "LO"
	LongText            = "LT"
	OtherByteString     = "OB"
	OtherDoubleString   = "OD"
	OtherFloatString    = "OF"
	OtherWordString     = "OW"
	PersonName          = "PN"
	ShortString         = "SH"
	SignedLong          = "SL"
	SequenceOfItems     = "SQ"
	SignedShort         = "SS"
	ShortText           = "ST"
	Time                = "TM"
	UniqueIdentifier    = "UI"
	UnsignedLong        = "UL"
	Unknown             = "UN"
	UnsignedShort       = "US"
	UnlimitedText       = "UT"
)
