package modality

const (
	CR       = "Computed Radiography"
	CT       = "Computed Tomography"
	MR       = "Magnetic Resonance"
	US       = "Ultrasound"
	OT       = "Other"
	BI       = "Biomagnetic imaging"
	CD       = "Color flow Doppler"
	DD       = "Duplex Doppler"
	DG       = "Diaphanography"
	ES       = "Endoscopy"
	LS       = "Laser surface scan"
	PT       = "Positron emission tomography (PET)"
	RG       = "Radiographic imaging (conventional film/screen)"
	ST       = "Single-photon emission computed tomography (SPECT)"
	TG       = "Thermography"
	XA       = "X-Ray Angiography"
	RF       = "Radio Fluoroscopy"
	RTIMAGE  = "Radiotherapy Image"
	RTDOSE   = "Radiotherapy Dose"
	RTSTRUCT = "Radiotherapy Structure Set"
	RTPLAN   = "Radiotherapy Plan"
	RTRECORD = "RT Treatment Record"
	HC       = "Hard Copy"
	DX       = "Digital Radiography"
	NM       = "Nuclear Medicine"
	MG       = "Mammography"
	IO       = "Intra-oral Radiography"
	PX       = "Panoramic X-Ray"
	GM       = "General Microscopy"
	SM       = "Slide Microscopy"
	XC       = "External-camera Photography"
	PR       = "Presentation State"
	AU       = "Audio ECG"
	EPS      = "Cardiac Electrophysiology"
	HD       = "Hemodynamic Waveform"
	SR       = "SR Document"
	IVUS     = "Intravascular Ultrasound"
	OP       = "Ophthalmic Photography"
	SMR      = "Stereometric Relationship"
)
